### ISSUE TITLE
String index out of range + Value arrived out of order

### ISSUE THREAD

**Issue by Zomis** [Zomis/Brainduck#35]
Start the program and the FizzBuzz BF code appears. Press Ctrl + End and then try to write something and you get this:

    Exception in thread "JavaFX Application Thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -151
    	at java.lang.String.substring(String.java:1967)
    	at org.fxmisc.richtext.Paragraph.substring(Paragraph.java:73)
    	at org.fxmisc.richtext.StyledDocumentBase.sub(StyledDocumentBase.java:245)
    	at org.fxmisc.richtext.StyledDocumentBase.getText(StyledDocumentBase.java:51)
    	at org.fxmisc.richtext.EditableStyledDocument.lambda$null$24(EditableStyledDocument.java:129)
    	at org.reactfx.util.Tuple2.map(Tuple2.java:31)
    	at org.fxmisc.richtext.EditableStyledDocument.lambda$new$25(EditableStyledDocument.java:129)
    	at org.reactfx.MappedStream.lambda$observeInputs$201(MappedStream.java:22)
    	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
    	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
    	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
    	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
    	at org.reactfx.EventStreams$20.tryEmit(EventStreams.java:441)
    	at org.reactfx.EventStreams$20.lambda$observeInputs$36(EventStreams.java:436)
    	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
    	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
    	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
    	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
    	at org.reactfx.EventSource.push(EventSource.java:18)
    	at org.fxmisc.richtext.EditableStyledDocument.replace(EditableStyledDocument.java:454)
    	at org.fxmisc.richtext.EditableStyledDocument.replaceText(EditableStyledDocument.java:192)
    	at org.fxmisc.richtext.StyledTextArea.replaceText(StyledTextArea.java:720)
    	at org.fxmisc.richtext.TextEditingArea.replaceText(TextEditingArea.java:204)
    	at org.fxmisc.richtext.EditActions.replaceSelection(EditActions.java:119)
    	at org.fxmisc.richtext.skin.StyledTextAreaBehavior.keyTyped(StyledTextAreaBehavior.java:276)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$null$23(EventHandlerTemplate.java:156)
    	at java.util.Optional.ifPresent(Optional.java:159)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$act$24(EventHandlerTemplate.java:155)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$Builder.lambda$create$21(EventHandlerTemplate.java:117)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$17(EventHandlerTemplate.java:39)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$bind$14(EventHandlerTemplate.java:18)
    	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    	at javafx.event.Event.fireEvent(Event.java:198)
    	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
    	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
    	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
    	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
    	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:197)
    	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:147)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$354(GlassViewEventHandler.java:228)
    	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:227)
    	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
    	at com.sun.glass.ui.View.notifyKey(View.java:966)
    	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
    	at java.lang.Thread.run(Thread.java:745)
    Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Value arrived out of order: 4487
    	at org.reactfx.EventStreams$ExclusivePocket.set(EventStreams.java:671)
    	at org.reactfx.EventStreams$21.lambda$observeInputs$37(EventStreams.java:459)
    	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
    	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
    	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
    	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
    	at org.reactfx.EventSource.push(EventSource.java:18)
    	at org.fxmisc.richtext.EditableStyledDocument.replace(EditableStyledDocument.java:453)
    	at org.fxmisc.richtext.EditableStyledDocument.replaceText(EditableStyledDocument.java:192)
    	at org.fxmisc.richtext.StyledTextArea.replaceText(StyledTextArea.java:720)
    	at org.fxmisc.richtext.TextEditingArea.replaceText(TextEditingArea.java:204)
    	at org.fxmisc.richtext.EditActions.replaceSelection(EditActions.java:119)
    	at org.fxmisc.richtext.skin.StyledTextAreaBehavior.keyTyped(StyledTextAreaBehavior.java:276)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$null$23(EventHandlerTemplate.java:156)
    	at java.util.Optional.ifPresent(Optional.java:159)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$act$24(EventHandlerTemplate.java:155)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$Builder.lambda$create$21(EventHandlerTemplate.java:117)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$17(EventHandlerTemplate.java:39)
    	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$bind$14(EventHandlerTemplate.java:18)
    	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    	at javafx.event.Event.fireEvent(Event.java:198)
    	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
    	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
    	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
    	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
    	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:197)
    	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:147)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$354(GlassViewEventHandler.java:228)
    	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:227)
    	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
    	at com.sun.glass.ui.View.notifyKey(View.java:966)
    	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    	at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by Zomis** [comment]
Added a work around until later. Seems like it is only needed to click that button once, then everything works. Look into this problem again at a later time.
